// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Link$ReactTemplate = require("./Link.bs.js");
var Header$ReactTemplate = require("./Header.bs.js");

var component = ReasonReact.reducerComponent("App");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var sortedLinks = List.sort((function (param, param$1) {
                      return param$1[1][/* rating */2] - param[1][/* rating */2] | 0;
                    }), self[/* state */1][/* links */0]);
              return React.createElement("div", {
                          style: {
                            display: "flex",
                            fontFamily: "omnes-pro, sans-serif",
                            fontSize: "1.2em",
                            lineHeight: "1.4em",
                            width: "100%",
                            alignItems: "center",
                            flexDirection: "column"
                          }
                        }, ReasonReact.element(undefined, undefined, Header$ReactTemplate.make(/* array */[])), $$Array.of_list(List.mapi((function (index, param) {
                                    var match = param[1];
                                    return ReasonReact.element(String(param[0]), undefined, Link$ReactTemplate.make(/* array */[], index, match[/* title */1], match[/* rating */2], match[/* url */0]));
                                  }), sortedLinks)));
            }),
          /* initialState */(function () {
              return /* record */[/* links : :: */[
                        /* tuple */[
                          1,
                          /* record */[
                            /* url */"https://google.com",
                            /* title */"Google",
                            /* rating */0
                          ]
                        ],
                        /* :: */[
                          /* tuple */[
                            2,
                            /* record */[
                              /* url */"https://reddit.com",
                              /* title */"Reddit",
                              /* rating */5
                            ]
                          ],
                          /* :: */[
                            /* tuple */[
                              3,
                              /* record */[
                                /* url */"https://news.ycombinator.com",
                                /* title */"Hacker News",
                                /* rating */10
                              ]
                            ],
                            /* [] */0
                          ]
                        ]
                      ]];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              return /* Update */Block.__(0, [/* record */[/* links */List.remove_assoc(action[0], state[/* links */0])]]);
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
